name: Python application

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pdf_to_csv/requirements.txt
        pip install pytest pytest-cov flake8
        
    - name: Lint with flake8
      run: |
        flake8 pdf_to_csv --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Test with pytest
      run: |
        # Skip tests if tests directory doesn't exist
        if [ -d "tests" ]; then
          pytest tests/ -v --cov=pdf_to_csv --cov-report=xml
        else
          echo "No tests directory found, skipping tests"
        fi
        
    - name: Upload coverage to Codecov
      if: success() && github.event_name != 'pull_request'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t pdf-to-csv:latest .
        
    - name: Test Docker image
      run: |
        docker run --rm pdf-to-csv:latest python -c "import streamlit; print('Streamlit OK')"
